### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by mcalux-cell** [Botrob72/Forager_ES_Spain_v1.0#1]
Hola muy buenas,

El proyecto no funciona,

Necesitais trabajarlo mas, cambiar 2 palabras no es hacer un mod.

Gracias

**Comment by Botrob72** [comment]
hola siento que no mi mod, lo intentare mejorar.

**Comment by mcalux-cell** [comment]
kys

**Comment by mcalux-cell** [comment]
El juego no funciona, no lo descarguen, les entrara 412 virus lo intente y mal
